platform :ios, '17.0'

source 'https://cdn.cocoapods.org/'

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

require Pod::Executable.execute_command(
  'node',
  [
    '-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      { paths: [process.argv[1]] }
    )',
    __dir__
  ]
).strip

prepare_react_native_project!

target 'ChildApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :fabric_enabled => true,
    :hermes_enabled => true
  )

  # В new architecture НІЯКИХ кастомних post_install не треба
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end